config/routes.rb
Rails.application.routes.draw do
  resources :customers

  root 'sessions#new'

  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'forgot_password' => 'sessions#forgot_password', as: 'forgot_password'
  post 'forgot_password' => 'sessions#reset_password', as: 'reset_password'
  get 'order/filter' => 'orders#filter', as: :order_filter
  get 'customer/filter' => 'customers#filter_customer', as: :filter_customer
  get 'user/role' => "users#role_filter"
  get 'customer/franchise' => 'customers#franchise_user'
  resources :orders do
    collection do 
      post :import
      get :import
      put :bulkupdate
    end
  end
  resources :products
  resources :users  
  resources :sessions

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  fname              :string(255)
#  lname              :string(255)
#  email              :string(255)
#  mobile             :integer
#  created_at         :datetime
#  updated_at         :datetime
#  password_digest    :string(255)
#  address            :text
#  id_pp              :string(255)
#  sex                :string(255)
#  disabled           :string(255)
#  race               :string(255)
#  agreed             :string(255)
#  phone              :string(255)
#  fax                :string(255)
#  starts_at          :datetime
#  ends_at            :datetime
#  role               :integer
#  owner_id           :integer
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  status             :boolean
#

class User < ActiveRecord::Base
  has_secure_password

  has_many :customers
  has_many :orders, through: :customers

  validates :fname, :lname, :email, presence: true

  #validate :password, :on => :create

  enum role: { admin: 0, franchise: 1, agent: 2 }

  belongs_to :owner, class_name: 'User'

  has_many :franchises, -> { where role: 1 }, class_name: 'User', foreign_key: :owner_id
  has_many :agents, -> { where role: 2 }, class_name: 'User', foreign_key: :owner_id

  has_attached_file :photo, :styles => { :medium => "200x200>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def full_name
    "#{fname} #{lname}"
  end

  def fullname
    full_name
  end

  def all_agents
    case role
    when "admin"
      User.where(role: 2)
    when "franchise"
      agents
    when "agent"
      self
    end
  end

  def scoped_customers
    case role
    when "admin"
      Customer.all
    when "franchise"
      Customer.where(user_id: agent_ids)
    when "agent"
      customers
    end
  end


  def scoped_orders

  end

def self.as_csv
  CSV.generate do |csv|
    csv << [ "Name", "Mobile", "Email", "Role", "Franchise Name"]
    all.each do |item|
     csv << [item.fullname, item.mobile, item.email, item.role, (item.owner.fname if item.owner.present?)]
    end
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = (policy_scope(User)).order("id desc").page params[:page]
    @users_csv = (policy_scope(User)).order("id desc")
    authorize @users, :index?

    respond_to do |format|
      format.html
      format.csv { send_data @users_csv.as_csv, :filename => 'organizations.csv' }
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user, :show?
  end

  def new
    @user = User.new
    authorize @user, :new?
  end


  def create
    @user = User.new(user_params)
    @roles = User.roles
    if @user.save
      redirect_to @user, notice: "User Created"
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @roles = User.roles
    authorize @user, :edit?
  end

  def update
    @user = User.find(params[:id])
    @roles = User.roles
        if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end
    if @user.update(user_params)
      redirect_to @user, notice: "User updated"
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: "User deleted"
  end

  def role_filter
    if params[:filter].present?
      role = User.roles[params[:filter][:role]]
      @users = User.where(role: role).page params[:page]
    end
    render 'index'
  end

  private
  def user_params
    params.require(:user).permit(:owner_id, :fname, :lname, :email, :password, :password_confirmation, :mobile, :address, :id_pp, :sex, :disabled, :race, :agreed, :phone, :fax, :starts_at, :ends_at, :status, :role, :photo)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="content">
  <% if @user.errors.any? %>
    <div id="errors" class="alert alert-danger">
      <p><strong>Please correct the following <%= pluralize(@user.errors.count, "error") %>:</strong></p>
      <ul>
	<% @user.errors.full_messages.each do |msg| %>
	  <li><%= msg  %></li>
	<% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :fname, "First Name" %>
      <div class="input-field">
	<%= f.text_field :fname, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :lname, "Last Name" %>
      <div class="input-field">
	<%= f.text_field :lname, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :photo %>
      <% if @user.photo.present? %>
        <%= image_tag @user.photo.url(:medium) %>
      <% end %>
      <div class="input-field">
        <%= f.file_field :photo %>
      </div>
    </div>
<fieldset>
  <p>Account Settings</p>
    <div class="form-group">

      <%= f.label :email %>
      <div class="input-field">
	<%= f.text_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :password %>
      <div class="input-field">
	<%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :passwordc %>
      <div class="input-field">
	<%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
</fieldset>
    <div class="form-group">

      <%= f.label :mobile %>
      <div class="input-field">
	<%= f.text_field :mobile, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :address %>
      <div class="input-field">
	<%= f.text_area :address, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :id_pp, "ID/PPNumber" %>
      <div class="input-field">
	<%= f.text_field :id_pp, class: 'form-control' %>
      </div>
    </div>



    <div class="form-group">

      <%= f.label :agreed, "Confirmation" %>
      <div class="input-field">
	<%= f.select(:agreed, ["Yes", "No"], {selected: "Yes"}, { :class => "form-control" })  %>
      </div>
    </div>

        <div class="form-group">

      <%= f.label :starts_at %>
      <div class="input-field">
        <%= f.text_field :starts_at, class: 'datepicker form-control' %>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :ends_at %>
      <div class="input-field">
        <%= f.text_field :ends_at, class: 'datepicker form-control' %>
      </div>
    </div>

    <div class="form-group">

      <% if current_user.admin? %>
        <%= f.label :role %>
        <div class="input-field">
          <%= f.select :role, collection: User.roles.keys %>
        </div>
      <% elsif current_user.franchise? %>
        <%= f.hidden_field :role, value: "agent" %>
      <% end %>

    </div>

    <div class="form-group">
      <label> Select Franchise if you have select "agent" from above role list</label>
      <div class="input-field">
        <%= f.select :owner_id, User.franchise.map {|user| [user.fname, user.id]}, {include_blank: "Please select"} if current_user.admin?%>
     </div>
    </div>
    <%= f.hidden_field :owner_id, value: current_user.id if current_user.franchise? %>

    <div class="form-group">

      <div class="input-field checkbox">&nbsp;&nbsp;&nbsp;
  <%= f.check_box :status %> Enabled
      </div>
    </div>
      <%= f.submit "Save", :class => "btn btn-success" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Organization</h1>
<%= render "form" %>

app/views/users/index.html.erb
<% if current_user.present? %>
<div class="btn-group pull-right">
<%= link_to 'Download CSV',users_path(format: :csv), class: 'btn btn-info' %> 
<% if policy(User.new).new? %>
<%= link_to 'New Organization', new_user_path, class: 'btn btn-success' %>
<% end %>
</div>
<% end  %>
<h1 class="page-header">Organization List</h1>
<% if current_user.present? && current_user.admin? %>
  <h5>Search</h3>
    <%= form_for :filter, url: user_role_path, method: :get, html: {class: 'inline-form' } do |f| %>
      <div class="form-group">
	<%= f.label :role %>
  <%= f.select :role, options_for_select(User.roles.keys), {}, class: 'form-control' %>
      </div>
	<%= f.submit 'Filter', class: 'btn btn-success' %>
    <% end %>
<% end %>
<table class="table">
  <tbody>
    <tr>
      <th> Name</th>
      <th> Mobile</th>
      <th> Email</th>
      <th> Role</th>
      <th> Created by</th>

    </tr>
    <% @users.each do |user| %>
      <tr>
	<td><%= link_to user.full_name, user %> </td>
	<td><%= user.mobile %></td>
	<td><%= user.email %></td>
	<td><%= user.role %></td>
  <td><%= user.owner.fname if user.owner.present? %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-md-2 col-md-offset-4">
<%= paginate @users %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-5">
    <h1>New Organization</h1>
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.fname %> <%= @user.lname %></h1>
<p><%= link_to "Edit", edit_user_path(@user), class: 'btn btn-success' %></p>
<div class="row">
<div class="col-md-6">
<% if @user.fname.present? %>
	<p>
	  <strong>First name: </strong>
	  <%= @user.fname %>
	</p>
<% end %>

<% if @user.lname.present? %>
	<p>
	  <strong>Last name: </strong>
	  <%= @user.lname %>
	</p>
<% end %>

<% if @user.mobile.present? %>
	<p>
	  <strong>Mobile: </strong>
	  <%= @user.mobile %>
	</p>
<% end %>

<% if @user.phone.present? %>
	<p>
	  <strong>Phone: </strong>
	  <%= @user.phone %>
	</p>
<% end %>

<% if @user.email.present? %>
	<p>
	  <strong>Email: </strong>
	  <%= @user.email %>
	</p>
<% end %>

<% if @user.address.present? %>
	<p>
	  <strong>Address: </strong>
	  <%= @user.address %>
	</p>
<% end %>

<% if @user.fax.present? %>
	<p>
	  <strong>Fax: </strong>
	  <%= @user.fax %>
	</p>
<% end %>

<% if @user.id_pp.present? %>
	<p>
	  <strong>ID/PP Number: </strong>
	  <%= @user.id_pp %>
	</p>
<% end %>

<% if @user.sex.present? %>
	<p>
	  <strong>Sex: </strong>
	  <%= @user.sex %>
	</p>
<% end %>

<% if @user.disabled.present? %>
	<p>
	  <strong>Disabled: </strong>
	  <%= @user.disabled %>
	</p>
<% end %>

<% if @user.race.present? %>
	<p>
	  <strong>Race: </strong>
	  <%= @user.race %>
	</p>
<% end %>

<% if @user.agreed.present? %>
	<p>
	  <strong>Confirm agreement: </strong>
	  <%= @user.agreed %>
	</p>
<% end %>

<% if @user.starts_at.present? %>
	<p>
	  <strong>Start Date: </strong>
	  <%= @user.starts_at %>
	</p>
<% end %>

<% if @user.ends_at.present? %>
	<p>
	  <strong>End Date: </strong>
	  <%= @user.ends_at %>
	</p>
<% end %>

<% if @user.status.present? %>
	<p>
	  <strong>Enabled: </strong>
	  <%= "#{@user.status}".capitalize %>
	</p>
<% else %>
	<p>
	  <strong>Enabled: </strong>
	  <%= "false".capitalize %>
	</p>
<% end %>
</div>
  <div class="col-md-6">
    <% if @user.photo.present? %>
    <%= image_tag @user.photo.url(:medium), class: 'img-thumbnail' %>
    <% else %>
      <%= image_tag 'no-image-available.jpeg', class: 'img-thumbnail' %>
    <% end %>
  </div>
   </div>