config/routes.rb
Rails.application.routes.draw do
  resources :customers

  root 'sessions#new'

  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'forgot_password' => 'sessions#forgot_password', as: 'forgot_password'
  post 'forgot_password' => 'sessions#reset_password', as: 'reset_password'
  get 'order/filter' => 'orders#filter', as: :order_filter
  get 'customer/filter' => 'customers#filter_customer', as: :filter_customer
  get 'user/role' => "users#role_filter"
  get 'customer/franchise' => 'customers#franchise_user'
  resources :orders do
    collection do 
      post :import
      get :import
      put :bulkupdate
    end
  end
  resources :products
  resources :users  
  resources :sessions

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id                  :integer          not null, primary key
#  first_name          :string(255)
#  last_name           :string(255)
#  mobile              :string(255)
#  address             :text
#  gps_location        :string(255)
#  id_pp               :string(255)
#  sex                 :integer
#  disabled            :boolean
#  race                :integer
#  number_in_household :integer
#  terms_agreed        :boolean
#  start_date          :date
#  end_date            :date
#  end_date_reason     :text
#  power_pack_paid     :boolean
#  lease_stove         :boolean
#  stove_number        :string(255)
#  installed           :boolean
#  fuel_cook           :hstore
#  fuel_heat           :hstore
#  created_at          :datetime
#  updated_at          :datetime
#  user_id             :integer
#  photo_file_name     :string(255)
#  photo_content_type  :string(255)
#  photo_file_size     :integer
#  photo_updated_at    :datetime
#

class Customer < ActiveRecord::Base
  # before_save :save_current_user_to_customer
  #   def save_current_user_to_customer
  #     self.user_id ||= session[:user_id]
  #   end
  store_accessor :fuel_cook, :cook_kerosene, :cook_coal, :cook_wood, :cook_charcoal, :cook_lpg, :cook_cng, :cook_electricity
  store_accessor :fuel_heat, :heat_kerosene, :heat_coal, :heat_wood, :heat_charcoal, :heat_lpg, :heat_cng, :heat_electricity

  GENDER_VALUES = [
    ['Male', 'male'],
    ['Female', 'female'],
    ['Transgender', 'transgender'],
  ]
  RACE_VALUES = [
   ["Black", 'black'],
   ["Asian", 'asian'],
   ["Indian", 'indian'],
   ["Coloured", 'coloured'],
   ["White", 'white'],
  ]
  belongs_to :user
  has_many :orders
  has_many :users, :through => :order
  has_attached_file :photo, :styles => { :medium => "200x200>" }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  validate :select_atleast_one_fuel_cook, :select_atleast_one_fuel_heat
  validates :first_name, :last_name, :address,:mobile, :id_pp, :user_id, :number_in_household, :terms_agreed, :start_date, presence: true
  validates :mobile, uniqueness: true


  def select_atleast_one_fuel_cook
    unless fuel_cook.drop_while {|i| i[1] == '0'}.present?
      errors.add(:fuel_cook, "Select at least one value")
    end
  end

    def select_atleast_one_fuel_heat
    unless fuel_heat.drop_while {|i| i[1] == '0'}.present?
      errors.add(:fuel_heat, "Select at least one value")
    end
  end



  def fullname
    "#{self.first_name} #{self.last_name}"
  end

  def full_name
    fullname
  end

  enum sex: %w(male female transgender)
  enum race: %w(black asian indian coloured white)

def self.as_csv
  CSV.generate do |csv|
    csv << [ "Customer Id", "First Name", "Last Name", "Customer Mobile", "Agent Id", "Agent Name", "Franchise Id", "Franchise Name"]
    all.each do |item|
     csv << [item.id, item.first_name, item.last_name, item.mobile, item.user_id, item.user.full_name, item.user.owner_id, item.user.owner.full_name]
    end
  end
end



end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  
  def index
    @mobiles = Customer.pluck(:mobile)
    @agents = User.where("role = ?", 2).pluck(:fname, :id)
    @franchises = User.where("role = ?", 1).pluck(:fname, :id)
    @customers_csv = (policy_scope Customer).order("id desc")
    @customers = (policy_scope Customer).order("id desc").page params[:page]
    authorize Customer.new, :index?
 
  respond_to do |format|
    format.html
    format.csv { send_data @customers_csv.as_csv }
  end


  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    authorize @customer, :show?
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    authorize @customer, :new?
  end

  # GET /customers/1/edit
  def edit
    authorize @customer, :edit?
  end
  def filter_customer
    @mobiles = Customer.pluck(:mobile)
    @agents = User.where("role = ?", 2).pluck(:fname, :id)
    @franchises = User.where("role = ?", 1).pluck(:fname, :id)
    @customers = policy_scope Customer
     if params[:search].present?
      if params[:search][:mobile].present? || params[:search][:agent].present? || params[:search][:franchise].present?
        mobile = params[:search][:mobile]
        agent = params[:search][:agent]
        franchise = params[:search][:franchise]
        if mobile.present?
          @customers = @customers.where(mobile: mobile).page params[:page]
        end
        if agent.present?
          @customers = @customers.where(user_id: agent).page params[:page]
        end
        if franchise.present?
          user = User.where(owner_id: franchise).pluck(:id)
          @customers = @customers.where(user_id: user).page params[:page]
        end
      else
        @customers = @customers.page(params[:page])
      end
    end
    render 'index' 
  end
  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    authorize @customer, :destroy?
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def franchise_user
    if params[:customer].present?
      user = params[:customer][:franchise_user]
      @customers = Customer.where(user: user)
    end
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :mobile, :address, :photo, :gps_location, :id_pp, :sex, :disabled, :race, :number_in_household, :terms_agreed, :start_date, :end_date, :end_date_reason, :power_pack_paid, :lease_stove, :stove_number, :installed, :fuel_cook, :cook_kerosene, :cook_coal, :cook_wood, :cook_charcoal, :cook_lpg, :cook_cng, :cook_electricity, :fuel_heat, :heat_kerosene, :heat_coal, :heat_wood, :heat_charcoal, :heat_lpg, :heat_cng, :heat_electricity, :user_id)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
<% if @customer.errors.any? %>
  <div id="errors"  class="alert alert-danger">
    <p><strong>Please correct the following <%= pluralize(@customer.errors.count, "error") %>:</strong></p>
    <ul>
      <% @customer.errors.full_messages.each do |msg| %>
      <li><%= msg  %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <% if @customer.photo.present? %>
      <%= image_tag @customer.photo.url(:medium) %>
    <% end %>
      <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :gps_location %><br>
    <%= f.text_field :gps_location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :id_pp, "ID/PPNumber" %><br>
    <%= f.text_field :id_pp, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :number_in_household %><br>
    <%= f.number_field :number_in_household %>
  </div>

  <div class="form-group">
    <%= f.check_box :terms_agreed %> <%= f.label :terms_agreed %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date, class: 'datepicker' %>
  </div>

  <div class="form-group">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date, class: 'datepicker' %>
  </div>

  <div class="form-group">
    <%= f.label :end_date_reason %><br>
    <%= f.text_area :end_date_reason, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.check_box :power_pack_paid %>
    <%= f.label :power_pack_paid %>
  </div>

  <div class="form-group">
    <%= f.check_box :lease_stove %>
    <%= f.label :lease_stove, "Own Stove" %>
  </div>

  <div class="form-group">
    <%= f.label :stove_number %>
    <%= f.text_field :stove_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.check_box :installed %> <%= f.label :installed %>
  </div>

    <div class="form-group">
    <label>Fuel used now to heat</label><br>
    <div class="checkbox">
      <label>
        <%= f.check_box :heat_kerosene %> Kerosene
      </label>

      <label>
        <%= f.check_box :heat_coal %> Coal
      </label>

      <label>
      <%= f.check_box :heat_wood %> Wood
      </label>

      <label>
      <%= f.check_box :heat_charcoal %> Charcoal
      </label>

      <label>
      <%= f.check_box :heat_lpg %> LPG
      </label>

      <label>
      <%= f.check_box :heat_cng %> CNG
      </label>

      <label>
      <%= f.check_box :heat_electricity %> Electricity
      </label>
    </div>
  </div>

  <div class="form-group">
    <label>Fuel used now to cook</label><br>
    <div class="checkbox">
      <label>
        <%= f.check_box :cook_kerosene %> Kerosene
      </label>

      <label>
        <%= f.check_box :cook_coal %> Coal
      </label>

      <label>
      <%= f.check_box :cook_wood %> Wood
      </label>

      <label>
      <%= f.check_box :cook_charcoal %> Charcoal
      </label>

      <label>
      <%= f.check_box :cook_lpg %> LPG
      </label>

      <label>
      <%= f.check_box :cook_cng %> CNG
      </label>

      <label>
      <%= f.check_box :cook_electricity %> Electricity
      </label>
    </div>
  </div>



    <% if current_user.agent? %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <% elsif %>
  <div class="form-group">
    <%= f.label :user_id, "Organization" %><br>
    <%= f.select :user_id, current_user.all_agents.pluck(:fname, :id), (@customer.user_id.nil? ? {:include_blank => "Select Agent"} : {:selected => @customer.user_id}) , { :class => "form-control" } %>

   </div>
  <% end %>

  <div class="actions">
    <p><%= f.submit :class => "btn btn-success" %></p>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

app/views/customers/index.html.erb
<% if current_user.present? %>
<div class="btn-group pull-right">
<%= link_to 'Download CSV', customers_path(format: :csv), class: 'btn btn-info' %> 
<%= link_to 'New Customer', new_customer_path, class: 'btn btn-success' %>
</div>
<% end  %>
        
         
<% if params[:search].present? 
      mobile_value = params[:search][:mobile]
      agent_value = params[:search][:agent]
      franchise_value = params[:search][:franchise]
      else
        var = " " 
      end 
%>

<h1 class="page-header">Customers List </h1> 
<%= form_for :search, url: filter_customer_path, method: :get, html: {class: 'form-inline customer-search'} do |f| %>
  <div class="form-group">
    <%= f.label "Mobile", class:"sr-only" %>
    <%= f.select :mobile, @mobiles.unshift(["Mobile Number", ""]), {:selected => mobile_value}, { :class => "form-control" } %>
  </div>
  <% if current_user.admin? %>
  <div class="form-group">
    <%= f.label "Agent", class:"sr-only" %>
    <%= f.select :agent, @agents.unshift(["Agent Name", ""]), {:selected => agent_value}, { :class => "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label "Franchise", class:"sr-only" %>
    <%= f.select :franchise, @franchises.unshift(["Franchise Name",""]), {:selected => franchise_value}, { :class => "form-control" }%>
  </div>
  <% end %>
  <%= f.submit "Filter", class: "btn btn-success" %>

<% end %>


<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Mobile</th>
      <th>Agent</th>
      <th>Franchise</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.first_name, customer %></td>
        <td><%= link_to customer.last_name, customer %></td>
        <td><%= customer.mobile %></td>
        <td><%= link_to customer.user.full_name, customer.user %></td>
        <td><%= link_to customer.user.owner.full_name, customer.user.owner %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-md-2 col-md-offset-4">
<%= paginate @customers %>
</div>

app/views/customers/new.html.erb
<div class="row">
<div class="col-md-5">
  <h1>New customer</h1>
  <%= render 'form' %>
</div>
</div>

app/views/customers/show.html.erb
<h1><%= @customer.fullname %></h1>
<p><%= link_to 'Edit', edit_customer_path(@customer), class: 'btn btn-success'  %> <%= link_to 'Delete', customer_path(@customer.id), :method => :delete, data: { confirm: 'Are you sure you want to delete this customer?' }, title: "Delete", class: "btn btn-danger"  %></p>


<div class="row">
<div class="col-md-6">
<% if @customer.first_name.present? %>
  <p>
    <strong>First name:</strong>
    <%= @customer.first_name %>
  </p>
<% end %>

<% if @customer.last_name.present? %>
  <p>
    <strong>Last name:</strong>
    <%= @customer.last_name %>
  </p>
<% end %>

<% if @customer.mobile.present? %>
  <p>
    <strong>Mobile:</strong>
    <%= @customer.mobile %>
  </p>
<% end %>

<% if @customer.address.present? %>
  <p>
    <strong>Address:</strong>
    <%= @customer.address %>
  </p>
<% end %>

<% if @customer.gps_location.present? %>
  <p>
    <strong>Gps location:</strong>
    <%= @customer.gps_location %>
  </p>
<% end %>

<% if @customer.id_pp.present? %>
  <p>
    <strong>Id pp:</strong>
    <%= @customer.id_pp %>
  </p>
<% end %>

<% if @customer.sex.present? %>
  <p>
    <strong>Sex:</strong>
    <%= @customer.sex %>
  </p>
<% end %>

<% if @customer.disabled.present? %>
  <p>
    <strong>Disabled:</strong>
    <%= @customer.disabled %>
  </p>
<% end %>

<% if @customer.race.present? %>
  <p>
    <strong>Race:</strong>
    <%= @customer.race %>
  </p>
<% end %>

<% if @customer.number_in_household.present? %>
  <p>
    <strong>Number in household:</strong>
    <%= @customer.number_in_household %>
  </p>
<% end %>

<% if @customer.terms_agreed.present? %>
  <p>
    <strong>Terms agreed:</strong>
    <%= @customer.terms_agreed %>
  </p>
<% end %>

<% if @customer.start_date.present? %>
  <p>
    <strong>Start date:</strong>
    <%= @customer.start_date %>
  </p>
<% end %>

<% if @customer.end_date.present? %>
  <p>
    <strong>End date:</strong>
    <%= @customer.end_date %>
  </p>
<% end %>

<% if @customer.end_date_reason.present? %>
  <p>
    <strong>End date reason:</strong>
    <%= @customer.end_date_reason %>
  </p>
<% end %>

<% if @customer.power_pack_paid.present? %>
  <p>
    <strong>Power pack paid:</strong>
    <%= @customer.power_pack_paid %>
  </p>
<% end %>

<% if @customer.lease_stove.present? %>
  <p>
    <strong>Own stove:</strong>
    <%= @customer.lease_stove %>
  </p>
<% end %>

<% if @customer.stove_number.present? %>
  <p>
    <strong>Stove number:</strong>
    <%= @customer.stove_number %>
  </p>
<% end %>

<% if @customer.installed.present? %>
  <p>
    <strong>Installed:</strong>
    <%= @customer.installed %>
  </p>
<% end %>

<% if @customer.fuel_heat.present? %>
   <p>
    <strong>Fuel for heating:</strong>
        <% @customer.fuel_heat.each do |value| %>
          <% if value[1] != '0' %>
            <br><%= value[0].gsub('heat_', '').humanize.capitalize %>
          <% end %>
        <% end %>
        <% #raise %>
  </p>
<% end %>

<% if @customer.fuel_cook.present? %>
  <p>
    <strong>Fuel for cooking:</strong>
    <% @customer.fuel_cook.each do |value| %>
      <% if value[1] != '0' %>
        <br><%= value[0].gsub('cook_', '').humanize.capitalize %>
      <% end %>
    <% end %>

  </p>
<% end %>

  <p>
    <strong>Agent Name:</strong>
    <%= link_to @customer.user.fname, @customer.user %>
    </p>
  </div>
  <div class="col-md-6">
    <% if @customer.photo.present? %>
    <%= image_tag @customer.photo.url(:medium), class: 'img-thumbnail' %>
    <% else %>
      <%= image_tag 'no-image-available.jpeg', class: 'img-thumbnail' %>
    <% end %>
  </div>
  </div>