config/routes.rb
Rails.application.routes.draw do
  resources :customers

  root 'sessions#new'

  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'forgot_password' => 'sessions#forgot_password', as: 'forgot_password'
  post 'forgot_password' => 'sessions#reset_password', as: 'reset_password'
  get 'order/filter' => 'orders#filter', as: :order_filter
  get 'customer/filter' => 'customers#filter_customer', as: :filter_customer
  get 'user/role' => "users#role_filter"
  get 'customer/franchise' => 'customers#franchise_user'
  resources :orders do
    collection do 
      post :import
      get :import
      put :bulkupdate
    end
  end
  resources :products
  resources :users  
  resources :sessions

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :integer          not null, primary key
#  status      :string(255)
#  product_id  :integer
#  customer_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#  reference   :string(255)
#

class Order < ActiveRecord::Base
  #before_save :default_values

  belongs_to :customer
  belongs_to :product

  validates :customer_id, :product_id, :status, :reference, presence: true
  STATUS = ["New", "Processing by Franchise", "Available for Agent", "Processing by Agent", "Delivered", "Complete", "Cancelled"]
  AGENT_STATUS = ["Processing by Agent", "Delivered"]
  FRANCHISE_STATUS = ["Processing by Franchise", "Available for Agent"]

  def self.import(file)
    message = []
    CSV.foreach(file.path) do |row|
      customer  = Customer.find_by(mobile: row[0])
      product = Product.find_by(price: row[1])
      if customer.present? && product.present?
        Order.create!(product: product, customer: customer, status: "New", reference: row[2])
      else
        message << "#{row[0]} and #{row[1]} and #{row[2]} "
      end
    end
    message
  end # end self.import(file)

  def self.as_csv(status=nil, from=nil, to=nil)
    CSV.generate do |csv|
      csv << [ 'Order Id', 'Mobile',  'Customer',  'Agent', 'Franchise', 'Product', 'Order Created Date',  'Status']
      conditions = {}
      conditions[:status] = status if status.present?
      conditions[:created_at] = from...to if from.present?
      self.where(conditions).each do |item|
        csv << [
          item.id,
          (item.customer.mobile rescue "Not Provided"),
          (item.customer.full_name  rescue "Not Provided"),
          (item.customer.user.full_name  rescue "Not Provided"),
          (item.customer.user.owner.full_name  rescue "Not Provided"),
          (item.product.name  rescue "Not Provided"), 
          item.created_at.strftime("%m/%d/%Y"),
          item.status
        ]
      end
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = (policy_scope(Order)).order("id desc").page params[:page]    
    authorize @orders, :index?
  end

  def show
    @order = Order.find(params[:id])
    authorize @order, :show?
  end

  def new
    @order = Order.new
    authorize @order, :new?
  end


  def create
    @order = Order.new(order_params)
    if @order.save
      #Usermailer.ordercreated_email(@order).deliver
      redirect_to @order, notice: "order Created"
    else
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      #if @order.status == "Available for Agent"
      #  Usermailer.orderforagent_email(@order).deliver
      #elsif @order.status == "Delivered"
       # Usermailer.orderdelivered_email(@order).deliver
      #elsif @order.status == "Complete"
       # Usermailer.ordercomplete_email(@order).deliver
      #elsif @order.status == "Cancelled"
       # Usermailer.ordercancelled_email(@order).deliver
      #end
      redirect_to @order, notice: "Order Updated"
    else
      render 'edit'
    end
  end

  def import
    authorize Order.new, :import?
    if params[:file].present?
      @message = Order.import(params[:file])
      @orders = policy_scope(Order).page params[:page]    
      render 'index'
    else
      redirect_to orders_path
      flash[:error] = "Choose a CSV file before importing"
    end

  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_url, notice: "Order Deleted"
  end

  def bulkupdate
    condition = {}
    condition[:id] = params[:order_id]
    if current_user.franchise? 
      condition[:status] = ["New", "Processing by Franchise", "Available for Agent"]
    elsif current_user.agent? 
      condition[:status] = ["Available for Agent"] + Order::AGENT_STATUS
    end
    Order.where(condition).update_all( :status => params[:bulkupdate][:status])
    flash[:notice] = "Orders that are open for update are updated."
    redirect_to orders_url
  end

  def export
  end

  def filter
    @orders = policy_scope(Order)

    if params[:search].present?
      status = params[:search][:status]
      from = params[:search][:start_date]
      to = params[:search][:end_date]
      to = Time.now unless to.present?
    
      if(params[:commit] == 'Export As CSV') 
        send_data Order.as_csv(status, from, to), :filename => 'orders.csv'
      else
        if status.present?
          @orders = @orders.where(status: status)
        end
        if from.present? 
          if from == to 
            @orders = @orders.where(created_at: (from.to_datetime.beginning_of_day)..(to.to_datetime.end_of_day))
          else
            @orders = @orders.where(created_at: from...to)
          end
        end
        @orders = @orders.page params[:page]
        render "index"
      end
    end
  end

private

def order_params
  params.require(:order).permit(:status, :product_id, :customer_id, :reference)
end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="content">
  <% if @order.errors.any? %>
    <div id="errors" class="alert alert-danger">
      <p><strong>Please correct the following <%= pluralize(@order.errors.count, "error") %>:</strong></p>
      <ul>
	<% @order.errors.full_messages.each do |msg| %>
	  <li><%= msg  %></li>
	<% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @order do |f| %>
    <div class="form-group">
      <%= f.label :customer_id, "Mobile"%>
      <%= f.collection_select(:customer_id, Customer.all, :id, :mobile, {prompt: true}, { :class => "form-control" })%>
    </div>

    <div class="form-group">
      <%= f.label :product_id, "Price" %>
      <%= f.collection_select(:product_id, Product.all, :id, :price, {prompt: true}, { :class => "form-control" }) %>
    </div>
      
    <div class="form-group">
      <%= f.label :reference %>
      <div class="input-field">
      <%= f.text_field :reference, class: 'form-control' %>
      </div>
    </div>
	<%= f.hidden_field :status, value: "New" %>
      <%= f.submit :class => "btn btn-success" %>
  <% end %>
</div>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= render "form" %>

app/views/orders/index.html.erb
<% if @message.present? %>
  <div id="errors">
    <h1>Order Import Error</h1>
    <p>Following <%= pluralize(@message.count, "order") %> didn't import properly. Either no matching customer found or value mismatch.</p>
    <ul>
      <% @message.each do |msg| %>
        <li><%= msg  %></li>
      <% end %>
    </ul>
<% end %>

<% if current_user.admin? %>
  <div class="row">
    <div class="col-md-2 col-md-offset-3">
      <% if policy(Order.new).new? %>
        <%= link_to "Create an order", new_order_path, class: 'btn btn-success' %> <span class="pull-right">OR</span>
      <% end %>
    </div>
    <div class="col-md-6">
      <%= form_tag import_orders_path, multipart: true, class: 'form-inline' do %>
        <div class="form-group">
          <%= file_field_tag :file%>
        </div>
        <%= submit_tag "Import orders from CSV", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
<% end %>
<h1>List of Orders</h1>
<p class="lead">Filter orders by</p>
<%= form_for :search, url: order_filter_path, method: :get, html: {class: 'form-inline'} do |f| %>
  <div class="form-group">
    <%= f.label "Status", class:"sr-only" %>
    <%= f.select :status, options_for_select(Order::STATUS, selected: (params[:search][:status] if params[:search].present?)), {include_blank: "Order Status"}, { :class => "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label  "From date", class: 'sr-only' %>
    <%= f.text_field :start_date, class: 'datepicker form-control', placeholder: 'From date', value: (params[:search][:start_date] if params[:search].present?) %>
  </div>
  <div class="form-group">
    <%= f.label  "To date", class: 'sr-only' %>
    <%= f.text_field :end_date, class: 'datepicker form-control', placeholder: 'To date', value: (params[:search][:end_date] if params[:search].present?)  %>
  </div>
  <%= f.submit "Filter", class: "btn btn-success" %>
   <%= f.submit "Export As CSV", class: "btn btn-info" %>
<% end %>
<hr/>
<%= form_for :bulkupdate, url: bulkupdate_orders_path, method: :put, html: {class: 'form-inline'} do |f| %>

<table class="table">
  <tbody>
    <tr>
      <th> # </th>
      <th> Order Id</th>
      <th> Mobile</th>
      <th> Customer</th>
      <th> Agent</th>
      <th> Franchise</th>
      <th> Product</th>
      <th> Order Created Date</th>
      <th> Status</th>
    </tr>
    <% @orders.each do |order| %>
    <tr>
      <td><%= check_box_tag "order_id[]", order.id %></td>
	    <td><%= link_to "Order #{order.id}", order %></td>
	    <td><%= order.customer.mobile %></td>
	    <td><%= order.customer.first_name rescue nil %> <%= order.customer.last_name rescue nil %></td>
	    <td><%= order.customer.user.full_name  rescue nil %></td>
      <td><%= order.customer.user.owner.full_name rescue nil %></td>
	    <td><%= order.product.name rescue "No Matching Product" %></td>
      <td><%= order.created_at.strftime("%m/%d/%Y") %></td>
	    <td><%= order.status %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<hr/>
<div class="form-group">
  <%= f.label :status, "Order Status" %>
  <div class="form-group">
    <% if current_user.admin? %>
     <%= f.select(:status, Order::STATUS, {}, class: 'form-control') %>
    <% elsif current_user.franchise? %>
      <%= f.select(:status, Order::FRANCHISE_STATUS, {}, class: 'form-control') %>
    <% elsif current_user.agent? %>
      <%= f.select(:status, Order::AGENT_STATUS, {}, class: 'form-control') %>
    <% end %>
  </div>
</driv>
<%= f.submit "Bulk Update", class: "btn btn-success" %>
<% end %>
<div class="col-md-2 col-md-offset-4">
<%= paginate @orders %>
</div>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-md-5">
    <h1>New Order</h1>
    <%= render "form" %>
  </div>
</div>

app/views/orders/show.html.erb
<h1>Order<%= @order.id %></h1>
<p><%= link_to "Edit", edit_order_path(@order), class: 'btn btn-success' %></p>
<div class="row">
  <div class="col-md-5">
    <p><strong>Customer: </strong><%= link_to @order.customer.fullname, @order.customer %></p>
    <p><strong>Mobile: </strong><%= @order.customer.mobile %></p>
    <p><strong>Product: </strong><%= @order.product.name %></p>
    <p><strong>Price: </strong><%= @order.product.price %></p>
    <p><strong>Order Created on: </strong><%= @order.created_at.strftime("%m/%d/%Y") %></p>
    <p><strong>Status: </strong><%= @order.status %></p>

    <% if current_user.admin? %>
      <%= form_for @order do |f| %>
        <div class="form-group">
          <%= f.label :status %>
          <div class="form-group">
    	       <%= f.select(:status, Order::STATUS, {}, class: 'form-control') %>
          </div>
        </div>
        <div class="actions">
          <%= f.submit 'Update', class: 'btn btn-success' %>
        </div>
      <% end %>
    <% elsif current_user.franchise? && (@order.status == "New" || (Order::FRANCHISE_STATUS.include? @order.status)) %>
      <%= form_for @order do |f| %>
        <div class="form-group">
          <%= f.label :status %>
          <div class="form-group">
             <%= f.select(:status, Order::FRANCHISE_STATUS, {}, class: 'form-control') %>
          </div>
        </div>
        <div class="actions">
          <%= f.submit 'Update', class: 'btn btn-success' %>
        </div>
      <% end %>
    <% elsif current_user.agent? && (@order.status == "Available for Agent" || (Order::AGENT_STATUS.include? @order.status)) %>
      <%= form_for @order do |f| %>
        <div class="form-group">
          <%= f.label :status %>
          <div class="form-group">
             <%= f.select(:status, Order::AGENT_STATUS, {}, class: 'form-control') %>
           </div>
        </div>
        <div class="actions">
          <%= f.submit 'Update', class: 'btn btn-success' %>
        </div>
      <% end %>
    <% else %>
    <% end %>
  </div>
</div>